.travis.gocyclo.sh, .travis.gofmt.sh, .travis.golint.sh, .travis.govet.sh, .travis.yml, README.md, auth/auth.go, main.go, server/auth.go, server/server.go, utils/response.go
- Added travis style checks
- Fixed semantic and syntax errors
=> Configured CI

auth/auth.go, server/auth.go, server/proxy.go
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #18 
Please delete options that are not relevant.
This change does not actually change the real source code, so no further testing is needed.
=> Add missing license headers

.travis.yml, README.md
Ability to display code coverage on codecov.io
Fixes #24
Just run `go test ./...` as usual
=> Codecov io setup

README.md, server/server.go, utils/utils.go
Added env variable for setting API_PREFIX.
Testing could be made by changing `CONTROLLER_PREFIX` variable.
=> Added getting prefix path from env variable

Dockerfile
Added internal Red Hat IT certificate into image.
=> Added RH-IT-Root-CA certificate into image

Makefile, docs/Gemfile, docs/README.md, docs/_config.yml, docs/index.md, docs/packages/auth/auth.html, docs/packages/auth/auth_test.html, docs/packages/main.html, docs/packages/server/auth.html, docs/packages/server/auth_test.html, docs/packages/server/proxy.html, docs/packages/server/server.html
Documentation in literate programming style
Fixes #35
=> Documentation in literate programming style

abcgo.sh, goconst.sh, gocyclo.sh, goerrcheck.sh, golint.sh, gosec.sh, ineffassign.sh
Don't install any already installed go tools
Fixes #37 #38 #39 #40 #41 #42 #43
=> Don't install any already installed go tools

server/proxy.go
Added two missing error checks.
Fixes #32
N/A
=> Added two missing error checks

README.md
Tags in README reformatted
N/A
=> Tags in README reformatted

Makefile
License generator in Makefile
Fixes #58
N/A
=> License generator in Makefile

docs/packages/auth/auth.html, docs/packages/auth/auth_test.html, docs/packages/main.html, docs/packages/server/auth.html, docs/packages/server/auth_test.html, docs/packages/server/proxy.html, docs/packages/server/server.html
Files with generated documentation should contain License header
Fixes #57
N/A
=> Files with generated documentation should contain License header

.travis.yml, Dockerfile, gofmt.sh, golint.sh, govet.sh
All shell scripts should contain proper License header
Fixes #61
N/A
=> All shell scripts should contain proper License header

docs/packages/server/server.html, server/server.go
Add package description into `server/server.go`
Fixes #67
N/A
=> Add package description into `server/server.go`

auth/auth.go, docs/packages/auth/auth.html
Added package description into `auth/auth.go`
Fixes #65
N/A
=> Added package description into `auth/auth.go`

docs/packages/main.html, main.go
Added package description into `main.go`
Fixes #63
N/A
=> Added package description into `main.go`

README.md
Links to GoDoc pages + GitHub pages as well
Fixes #56
N/A
=> Links to GoDoc pages + GitHub pages as well

.gitignore
=> Ignore issue checker

docs/packages/main.html, main.go
Documentation update
Fixes #76
N/A
=> Fix issue #76

auth/auth.go, docs/packages/auth/auth.html
Documentation update
Fixes #77
N/A
=> Fix issue 77

auth/auth_test.go, docs/packages/auth/auth_test.html
Documentation update
Fixes #78
N/A
=> Fix issue #78

docs/packages/server/auth.html, server/auth.go
Documentation update.
Fixes #79
N/A
=> Fix issue #79

docs/packages/server/auth_test.html, server/auth_test.go
Documentation update.
Fixes #80
N/A
=> Fix issue 80

docs/packages/server/proxy.html, server/proxy.go
Documentation update.
Fixes #81
N/A
=> Fix issue #81

docs/packages/server/server.html, server/server.go
Documentation update.
Fixes #82
N/A
=> Fix issue #82

CODEOWNERS
List of code owners
Fixes #90
- Administration task
N/A
=> List of code owners

CODEOWNERS
Add Papa Bakary Camara into owner list
Fixes #92
N/A
=> Add Papa Bakary Camara into owner list

server/server.go
Removed unused code
- Refactor (refactoring code, removing useless files)
Done on CI
=> Removed unused code

auth/auth.go, auth/auth_test.go, go.mod, main.go, server/auth.go
Fix minor issues
- Refactor (refactoring code, removing useless files)
Done on CI
=> Fix minor issues

.travis.yml
=> Build step on CI

DoD.md, README.md
=> Definition of Done

docs/packages/auth/auth.html, docs/packages/auth/auth_test.html, docs/packages/main.html, docs/packages/server/auth.html, docs/packages/server/server.html
=> Regenerated docs

golint.sh
Fixed issue found by shellcheck.
Fixes https://github.com/RedHatInsights/insights-results-aggregator/issues/1560
To be checked on CI later.
=> Fix issue #1560

shellcheck.sh
Incorporate shellcheck
N/A ATM
=> Incorporate shellcheck

golint.sh
Fix issue #1561
Fixes https://github.com/RedHatInsights/insights-results-aggregator/issues/1561
To be checked on CI soon.
=> Fix issue #1561

govet.sh
Fix issue #1562
Fixes (https://github.com/RedHatInsights/insights-results-aggregator/issues/1562)
N/A ATM
=> Fix issue #1562

govet.sh
Fixes bug found by shellcheck
Fixes [# 1563](https://github.com/RedHatInsights/insights-results-aggregator/issues/1563)
N/A
=> Fix issue #1563

shellcheck.sh
Fixed shellcheck script
Done on CI
=> Fixed shellcheck script

server/auth.go
Fixed huge param issue #143
Fixes #143
Done on CI
=> Fixed huge param issue #143

server/auth.go
Fixed huge param issue #144
Fixes #144
Done on CI
=> Fixed huge param issue #144

server/server.go
Fixed huge param issue #147
Fixes #147
Done on CI
=> Fixed huge param issue #147

server/server.go
Fixed huge param issue #146
Fixes #146
Done on CI
=> Fixed huge param issue #146

gosec.sh
Verbose `gosec` installation
Fixes #120
Fixes #121
Fixes #150
Done on CI
=> Verbose gosec installation

abcgo.sh, goconst.sh, gocyclo.sh, goerrcheck.sh, gofmt.sh, golint.sh, govet.sh
=> Colorful CI
